// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"time"
)

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS(SELECT 1 FROM categories WHERE id = ?)
`

func (q *Queries) CategoryExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, categoryExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const categoryExistsByName = `-- name: CategoryExistsByName :one
SELECT EXISTS(SELECT 1 FROM categories WHERE name = ?)
`

func (q *Queries) CategoryExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, categoryExistsByName, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name, description
) VALUES (
    ?, ?
)
RETURNING id, name, description, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteCategoryByName = `-- name: DeleteCategoryByName :exec
DELETE FROM categories
WHERE name = ?
`

func (q *Queries) DeleteCategoryByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryByName, name)
	return err
}

const getCategoriesCreatedAfter = `-- name: GetCategoriesCreatedAfter :many
SELECT id, name, description, created_at, updated_at FROM categories
WHERE created_at > ?
ORDER BY created_at DESC
`

func (q *Queries) GetCategoriesCreatedAfter(ctx context.Context, createdAt *time.Time) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesCreatedAfter, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesUpdatedAfter = `-- name: GetCategoriesUpdatedAfter :many
SELECT id, name, description, created_at, updated_at FROM categories
WHERE updated_at > ?
ORDER BY updated_at DESC
`

func (q *Queries) GetCategoriesUpdatedAfter(ctx context.Context, updatedAt *time.Time) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesUpdatedAfter, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, description, created_at, updated_at FROM categories
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, description, created_at, updated_at FROM categories
WHERE name = ? LIMIT 1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, created_at, updated_at FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithLimit = `-- name: ListCategoriesWithLimit :many
SELECT id, name, description, created_at, updated_at FROM categories
ORDER BY name
LIMIT ? OFFSET ?
`

type ListCategoriesWithLimitParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCategoriesWithLimit(ctx context.Context, arg ListCategoriesWithLimitParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesWithLimit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCategories = `-- name: SearchCategories :many
SELECT id, name, description, created_at, updated_at FROM categories
WHERE name LIKE ? OR description LIKE ?
ORDER BY name
`

type SearchCategoriesParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, searchCategories, arg.Name, arg.Description)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = ?,
    description = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.Name, arg.Description, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryDescription = `-- name: UpdateCategoryDescription :one
UPDATE categories
SET description = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, created_at, updated_at
`

type UpdateCategoryDescriptionParams struct {
	Description *string `json:"description"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateCategoryDescription(ctx context.Context, arg UpdateCategoryDescriptionParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategoryDescription, arg.Description, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryName = `-- name: UpdateCategoryName :one
UPDATE categories
SET name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, created_at, updated_at
`

type UpdateCategoryNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCategoryName(ctx context.Context, arg UpdateCategoryNameParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategoryName, arg.Name, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
