// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Category struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64      `json:"id"`
	UserID    int64      `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	Revoked   int64      `json:"revoked"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Subscription struct {
	ID                 int64      `json:"id"`
	CategoryID         int64      `json:"category_id"`
	Name               string     `json:"name"`
	Description        *string    `json:"description"`
	Cost               float64    `json:"cost"`
	Currency           *string    `json:"currency"`
	BillingCycle       string     `json:"billing_cycle"`
	NextBillingDate    time.Time  `json:"next_billing_date"`
	StartDate          time.Time  `json:"start_date"`
	EndDate            *time.Time `json:"end_date"`
	Status             *string    `json:"status"`
	AutoRenew          *bool      `json:"auto_renew"`
	ReminderEnabled    *bool      `json:"reminder_enabled"`
	ReminderDaysBefore *int64     `json:"reminder_days_before"`
	PaymentMethod      *string    `json:"payment_method"`
	Notes              *string    `json:"notes"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}

type User struct {
	ID        int64      `json:"id"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type UsersCategory struct {
	ID         int64      `json:"id"`
	UserID     int64      `json:"user_id"`
	CategoryID int64      `json:"category_id"`
	CreatedAt  *time.Time `json:"created_at"`
	UpdatedAt  *time.Time `json:"updated_at"`
}

type UsersSubscription struct {
	ID             int64      `json:"id"`
	UserID         int64      `json:"user_id"`
	SubscriptionID int64      `json:"subscription_id"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}
