// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"time"
)

type Querier interface {
	ActivateSubscription(ctx context.Context, id int64) (Subscription, error)
	CalculateTotalMonthlyCost(ctx context.Context, currency *string) (*float64, error)
	CalculateTotalYearlyCost(ctx context.Context, currency *string) (*float64, error)
	CancelSubscription(ctx context.Context, id int64) (Subscription, error)
	CategoryExists(ctx context.Context, id int64) (int64, error)
	CategoryExistsByName(ctx context.Context, name string) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountSubscriptions(ctx context.Context) (int64, error)
	CountSubscriptionsByCategory(ctx context.Context, categoryID int64) (int64, error)
	CountSubscriptionsByStatus(ctx context.Context, status *string) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteCategoryByName(ctx context.Context, name string) error
	DeleteSubscription(ctx context.Context, id int64) error
	GetCategoriesCreatedAfter(ctx context.Context, createdAt *time.Time) ([]Category, error)
	GetCategoriesUpdatedAfter(ctx context.Context, updatedAt *time.Time) ([]Category, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetExpiredSubscriptions(ctx context.Context) ([]Subscription, error)
	GetModifiedSubscriptions(ctx context.Context, updatedAt *time.Time) ([]Subscription, error)
	GetRecentSubscriptions(ctx context.Context, createdAt *time.Time) ([]Subscription, error)
	GetSubscription(ctx context.Context, id int64) (Subscription, error)
	GetSubscriptionStatsByCategory(ctx context.Context) ([]GetSubscriptionStatsByCategoryRow, error)
	GetSubscriptionWithCategory(ctx context.Context, id int64) (GetSubscriptionWithCategoryRow, error)
	GetSubscriptionsBetweenDates(ctx context.Context, arg GetSubscriptionsBetweenDatesParams) ([]Subscription, error)
	GetSubscriptionsByAutoRenew(ctx context.Context, autoRenew *bool) ([]Subscription, error)
	GetSubscriptionsDueForRenewal(ctx context.Context, nextBillingDate time.Time) ([]Subscription, error)
	GetSubscriptionsWithReminders(ctx context.Context, nextBillingDate time.Time) ([]Subscription, error)
	GetUpcomingRenewals(ctx context.Context, dollar_1 *string) ([]Subscription, error)
	ListActiveSubscriptions(ctx context.Context) ([]Subscription, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesWithLimit(ctx context.Context, arg ListCategoriesWithLimitParams) ([]Category, error)
	ListSubscriptions(ctx context.Context) ([]Subscription, error)
	ListSubscriptionsByBillingCycle(ctx context.Context, billingCycle string) ([]Subscription, error)
	ListSubscriptionsByCategory(ctx context.Context, categoryID int64) ([]Subscription, error)
	ListSubscriptionsByStatus(ctx context.Context, status *string) ([]Subscription, error)
	ListSubscriptionsWithCategories(ctx context.Context) ([]ListSubscriptionsWithCategoriesRow, error)
	ListSubscriptionsWithLimit(ctx context.Context, arg ListSubscriptionsWithLimitParams) ([]Subscription, error)
	PauseSubscription(ctx context.Context, id int64) (Subscription, error)
	SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error)
	SearchSubscriptions(ctx context.Context, arg SearchSubscriptionsParams) ([]Subscription, error)
	SubscriptionExists(ctx context.Context, id int64) (int64, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryDescription(ctx context.Context, arg UpdateCategoryDescriptionParams) (Category, error)
	UpdateCategoryName(ctx context.Context, arg UpdateCategoryNameParams) (Category, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	UpdateSubscriptionCost(ctx context.Context, arg UpdateSubscriptionCostParams) (Subscription, error)
	UpdateSubscriptionNextBillingDate(ctx context.Context, arg UpdateSubscriptionNextBillingDateParams) (Subscription, error)
	UpdateSubscriptionReminder(ctx context.Context, arg UpdateSubscriptionReminderParams) (Subscription, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
