// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package database

import (
	"context"
	"time"
)

const activateSubscription = `-- name: ActivateSubscription :one
UPDATE subscriptions
SET status = 'active',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

func (q *Queries) ActivateSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, activateSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const calculateTotalMonthlyCost = `-- name: CalculateTotalMonthlyCost :one
SELECT SUM(
    CASE billing_cycle
        WHEN 'daily' THEN cost * 30
        WHEN 'weekly' THEN cost * 4.33
        WHEN 'monthly' THEN cost
        WHEN 'quarterly' THEN cost / 3
        WHEN 'yearly' THEN cost / 12
    END
) as total_monthly_cost
FROM subscriptions
WHERE status = 'active' AND currency = ?
`

func (q *Queries) CalculateTotalMonthlyCost(ctx context.Context, currency *string) (*float64, error) {
	row := q.db.QueryRowContext(ctx, calculateTotalMonthlyCost, currency)
	var total_monthly_cost *float64
	err := row.Scan(&total_monthly_cost)
	return total_monthly_cost, err
}

const calculateTotalYearlyCost = `-- name: CalculateTotalYearlyCost :one
SELECT SUM(
    CASE billing_cycle
        WHEN 'daily' THEN cost * 365
        WHEN 'weekly' THEN cost * 52
        WHEN 'monthly' THEN cost * 12
        WHEN 'quarterly' THEN cost * 4
        WHEN 'yearly' THEN cost
    END
) as total_yearly_cost
FROM subscriptions
WHERE status = 'active' AND currency = ?
`

func (q *Queries) CalculateTotalYearlyCost(ctx context.Context, currency *string) (*float64, error) {
	row := q.db.QueryRowContext(ctx, calculateTotalYearlyCost, currency)
	var total_yearly_cost *float64
	err := row.Scan(&total_yearly_cost)
	return total_yearly_cost, err
}

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions
SET status = 'cancelled',
    end_date = CURRENT_DATE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

func (q *Queries) CancelSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, cancelSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countSubscriptions = `-- name: CountSubscriptions :one
SELECT COUNT(*) FROM subscriptions
`

func (q *Queries) CountSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscriptionsByCategory = `-- name: CountSubscriptionsByCategory :one
SELECT COUNT(*) FROM subscriptions
WHERE category_id = ?
`

func (q *Queries) CountSubscriptionsByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscriptionsByStatus = `-- name: CountSubscriptionsByStatus :one
SELECT COUNT(*) FROM subscriptions
WHERE status = ?
`

func (q *Queries) CountSubscriptionsByStatus(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    category_id,
    name,
    description,
    cost,
    currency,
    billing_cycle,
    next_billing_date,
    start_date,
    end_date,
    status,
    auto_renew,
    reminder_enabled,
    reminder_days_before,
    payment_method,
    notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

type CreateSubscriptionParams struct {
	CategoryID         int64      `json:"category_id"`
	Name               string     `json:"name"`
	Description        *string    `json:"description"`
	Cost               float64    `json:"cost"`
	Currency           *string    `json:"currency"`
	BillingCycle       string     `json:"billing_cycle"`
	NextBillingDate    time.Time  `json:"next_billing_date"`
	StartDate          time.Time  `json:"start_date"`
	EndDate            *time.Time `json:"end_date"`
	Status             *string    `json:"status"`
	AutoRenew          *bool      `json:"auto_renew"`
	ReminderEnabled    *bool      `json:"reminder_enabled"`
	ReminderDaysBefore *int64     `json:"reminder_days_before"`
	PaymentMethod      *string    `json:"payment_method"`
	Notes              *string    `json:"notes"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Cost,
		arg.Currency,
		arg.BillingCycle,
		arg.NextBillingDate,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.AutoRenew,
		arg.ReminderEnabled,
		arg.ReminderDaysBefore,
		arg.PaymentMethod,
		arg.Notes,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = ?
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const getExpiredSubscriptions = `-- name: GetExpiredSubscriptions :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE end_date IS NOT NULL
  AND end_date < CURRENT_DATE
  AND status != 'cancelled'
ORDER BY end_date DESC
`

func (q *Queries) GetExpiredSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifiedSubscriptions = `-- name: GetModifiedSubscriptions :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE updated_at >= ?
ORDER BY updated_at DESC
`

func (q *Queries) GetModifiedSubscriptions(ctx context.Context, updatedAt *time.Time) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getModifiedSubscriptions, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSubscriptions = `-- name: GetRecentSubscriptions :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE created_at >= ?
ORDER BY created_at DESC
`

func (q *Queries) GetRecentSubscriptions(ctx context.Context, createdAt *time.Time) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getRecentSubscriptions, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionStatsByCategory = `-- name: GetSubscriptionStatsByCategory :many
SELECT
    c.name as category_name,
    COUNT(s.id) as subscription_count,
    SUM(s.cost) as total_cost,
    AVG(s.cost) as average_cost
FROM categories c
LEFT JOIN subscriptions s ON c.id = s.category_id AND s.status = 'active'
GROUP BY c.id, c.name
ORDER BY subscription_count DESC
`

type GetSubscriptionStatsByCategoryRow struct {
	CategoryName      string   `json:"category_name"`
	SubscriptionCount int64    `json:"subscription_count"`
	TotalCost         *float64 `json:"total_cost"`
	AverageCost       *float64 `json:"average_cost"`
}

func (q *Queries) GetSubscriptionStatsByCategory(ctx context.Context) ([]GetSubscriptionStatsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionStatsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubscriptionStatsByCategoryRow{}
	for rows.Next() {
		var i GetSubscriptionStatsByCategoryRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.SubscriptionCount,
			&i.TotalCost,
			&i.AverageCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionWithCategory = `-- name: GetSubscriptionWithCategory :one
SELECT
    s.id, s.category_id, s.name, s.description, s.cost, s.currency, s.billing_cycle, s.next_billing_date, s.start_date, s.end_date, s.status, s.auto_renew, s.reminder_enabled, s.reminder_days_before, s.payment_method, s.notes, s.created_at, s.updated_at,
    c.name as category_name,
    c.description as category_description
FROM subscriptions s
JOIN categories c ON s.category_id = c.id
WHERE s.id = ? LIMIT 1
`

type GetSubscriptionWithCategoryRow struct {
	ID                  int64      `json:"id"`
	CategoryID          int64      `json:"category_id"`
	Name                string     `json:"name"`
	Description         *string    `json:"description"`
	Cost                float64    `json:"cost"`
	Currency            *string    `json:"currency"`
	BillingCycle        string     `json:"billing_cycle"`
	NextBillingDate     time.Time  `json:"next_billing_date"`
	StartDate           time.Time  `json:"start_date"`
	EndDate             *time.Time `json:"end_date"`
	Status              *string    `json:"status"`
	AutoRenew           *bool      `json:"auto_renew"`
	ReminderEnabled     *bool      `json:"reminder_enabled"`
	ReminderDaysBefore  *int64     `json:"reminder_days_before"`
	PaymentMethod       *string    `json:"payment_method"`
	Notes               *string    `json:"notes"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
	CategoryName        string     `json:"category_name"`
	CategoryDescription *string    `json:"category_description"`
}

func (q *Queries) GetSubscriptionWithCategory(ctx context.Context, id int64) (GetSubscriptionWithCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionWithCategory, id)
	var i GetSubscriptionWithCategoryRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryDescription,
	)
	return i, err
}

const getSubscriptionsBetweenDates = `-- name: GetSubscriptionsBetweenDates :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE next_billing_date BETWEEN ? AND ?
ORDER BY next_billing_date ASC
`

type GetSubscriptionsBetweenDatesParams struct {
	FromNextBillingDate time.Time `json:"from_next_billing_date"`
	ToNextBillingDate   time.Time `json:"to_next_billing_date"`
}

func (q *Queries) GetSubscriptionsBetweenDates(ctx context.Context, arg GetSubscriptionsBetweenDatesParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsBetweenDates, arg.FromNextBillingDate, arg.ToNextBillingDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsByAutoRenew = `-- name: GetSubscriptionsByAutoRenew :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE auto_renew = ?
  AND status = 'active'
ORDER BY next_billing_date ASC
`

func (q *Queries) GetSubscriptionsByAutoRenew(ctx context.Context, autoRenew *bool) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByAutoRenew, autoRenew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsDueForRenewal = `-- name: GetSubscriptionsDueForRenewal :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE status = 'active'
  AND next_billing_date <= ?
ORDER BY next_billing_date ASC
`

func (q *Queries) GetSubscriptionsDueForRenewal(ctx context.Context, nextBillingDate time.Time) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsDueForRenewal, nextBillingDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsWithReminders = `-- name: GetSubscriptionsWithReminders :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE status = 'active'
  AND reminder_enabled = 1
  AND DATE(next_billing_date, '-' || reminder_days_before || ' days') <= ?
ORDER BY next_billing_date ASC
`

func (q *Queries) GetSubscriptionsWithReminders(ctx context.Context, nextBillingDate time.Time) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsWithReminders, nextBillingDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingRenewals = `-- name: GetUpcomingRenewals :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE status = 'active'
  AND next_billing_date BETWEEN CURRENT_DATE AND DATE(CURRENT_DATE, '+' || ? || ' days')
ORDER BY next_billing_date ASC
`

func (q *Queries) GetUpcomingRenewals(ctx context.Context, dollar_1 *string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingRenewals, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSubscriptions = `-- name: ListActiveSubscriptions :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE status = 'active'
ORDER BY next_billing_date ASC
`

func (q *Queries) ListActiveSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
ORDER BY next_billing_date ASC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByBillingCycle = `-- name: ListSubscriptionsByBillingCycle :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE billing_cycle = ?
ORDER BY next_billing_date ASC
`

func (q *Queries) ListSubscriptionsByBillingCycle(ctx context.Context, billingCycle string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByBillingCycle, billingCycle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByCategory = `-- name: ListSubscriptionsByCategory :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE category_id = ?
ORDER BY next_billing_date ASC
`

func (q *Queries) ListSubscriptionsByCategory(ctx context.Context, categoryID int64) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByStatus = `-- name: ListSubscriptionsByStatus :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE status = ?
ORDER BY next_billing_date ASC
`

func (q *Queries) ListSubscriptionsByStatus(ctx context.Context, status *string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsWithCategories = `-- name: ListSubscriptionsWithCategories :many
SELECT
    s.id, s.category_id, s.name, s.description, s.cost, s.currency, s.billing_cycle, s.next_billing_date, s.start_date, s.end_date, s.status, s.auto_renew, s.reminder_enabled, s.reminder_days_before, s.payment_method, s.notes, s.created_at, s.updated_at,
    c.name as category_name
FROM subscriptions s
JOIN categories c ON s.category_id = c.id
ORDER BY s.next_billing_date ASC
`

type ListSubscriptionsWithCategoriesRow struct {
	ID                 int64      `json:"id"`
	CategoryID         int64      `json:"category_id"`
	Name               string     `json:"name"`
	Description        *string    `json:"description"`
	Cost               float64    `json:"cost"`
	Currency           *string    `json:"currency"`
	BillingCycle       string     `json:"billing_cycle"`
	NextBillingDate    time.Time  `json:"next_billing_date"`
	StartDate          time.Time  `json:"start_date"`
	EndDate            *time.Time `json:"end_date"`
	Status             *string    `json:"status"`
	AutoRenew          *bool      `json:"auto_renew"`
	ReminderEnabled    *bool      `json:"reminder_enabled"`
	ReminderDaysBefore *int64     `json:"reminder_days_before"`
	PaymentMethod      *string    `json:"payment_method"`
	Notes              *string    `json:"notes"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
	CategoryName       string     `json:"category_name"`
}

func (q *Queries) ListSubscriptionsWithCategories(ctx context.Context) ([]ListSubscriptionsWithCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsWithCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsWithCategoriesRow{}
	for rows.Next() {
		var i ListSubscriptionsWithCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsWithLimit = `-- name: ListSubscriptionsWithLimit :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
ORDER BY next_billing_date ASC
LIMIT ? OFFSET ?
`

type ListSubscriptionsWithLimitParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSubscriptionsWithLimit(ctx context.Context, arg ListSubscriptionsWithLimitParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsWithLimit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseSubscription = `-- name: PauseSubscription :one
UPDATE subscriptions
SET status = 'paused',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

func (q *Queries) PauseSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, pauseSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchSubscriptions = `-- name: SearchSubscriptions :many
SELECT id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at FROM subscriptions
WHERE name LIKE ? OR description LIKE ? OR notes LIKE ?
ORDER BY next_billing_date ASC
`

type SearchSubscriptionsParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Notes       *string `json:"notes"`
}

func (q *Queries) SearchSubscriptions(ctx context.Context, arg SearchSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, searchSubscriptions, arg.Name, arg.Description, arg.Notes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionExists = `-- name: SubscriptionExists :one
SELECT EXISTS(SELECT 1 FROM subscriptions WHERE id = ?)
`

func (q *Queries) SubscriptionExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, subscriptionExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET category_id = ?,
    name = ?,
    description = ?,
    cost = ?,
    currency = ?,
    billing_cycle = ?,
    next_billing_date = ?,
    start_date = ?,
    end_date = ?,
    status = ?,
    auto_renew = ?,
    reminder_enabled = ?,
    reminder_days_before = ?,
    payment_method = ?,
    notes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	CategoryID         int64      `json:"category_id"`
	Name               string     `json:"name"`
	Description        *string    `json:"description"`
	Cost               float64    `json:"cost"`
	Currency           *string    `json:"currency"`
	BillingCycle       string     `json:"billing_cycle"`
	NextBillingDate    time.Time  `json:"next_billing_date"`
	StartDate          time.Time  `json:"start_date"`
	EndDate            *time.Time `json:"end_date"`
	Status             *string    `json:"status"`
	AutoRenew          *bool      `json:"auto_renew"`
	ReminderEnabled    *bool      `json:"reminder_enabled"`
	ReminderDaysBefore *int64     `json:"reminder_days_before"`
	PaymentMethod      *string    `json:"payment_method"`
	Notes              *string    `json:"notes"`
	ID                 int64      `json:"id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscription,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Cost,
		arg.Currency,
		arg.BillingCycle,
		arg.NextBillingDate,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.AutoRenew,
		arg.ReminderEnabled,
		arg.ReminderDaysBefore,
		arg.PaymentMethod,
		arg.Notes,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionCost = `-- name: UpdateSubscriptionCost :one
UPDATE subscriptions
SET cost = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

type UpdateSubscriptionCostParams struct {
	Cost float64 `json:"cost"`
	ID   int64   `json:"id"`
}

func (q *Queries) UpdateSubscriptionCost(ctx context.Context, arg UpdateSubscriptionCostParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriptionCost, arg.Cost, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionNextBillingDate = `-- name: UpdateSubscriptionNextBillingDate :one
UPDATE subscriptions
SET next_billing_date = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

type UpdateSubscriptionNextBillingDateParams struct {
	NextBillingDate time.Time `json:"next_billing_date"`
	ID              int64     `json:"id"`
}

func (q *Queries) UpdateSubscriptionNextBillingDate(ctx context.Context, arg UpdateSubscriptionNextBillingDateParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriptionNextBillingDate, arg.NextBillingDate, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionReminder = `-- name: UpdateSubscriptionReminder :one
UPDATE subscriptions
SET reminder_enabled = ?,
    reminder_days_before = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

type UpdateSubscriptionReminderParams struct {
	ReminderEnabled    *bool  `json:"reminder_enabled"`
	ReminderDaysBefore *int64 `json:"reminder_days_before"`
	ID                 int64  `json:"id"`
}

func (q *Queries) UpdateSubscriptionReminder(ctx context.Context, arg UpdateSubscriptionReminderParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriptionReminder, arg.ReminderEnabled, arg.ReminderDaysBefore, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, category_id, name, description, cost, currency, billing_cycle, next_billing_date, start_date, end_date, status, auto_renew, reminder_enabled, reminder_days_before, payment_method, notes, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	Status *string `json:"status"`
	ID     int64   `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateSubscriptionStatus, arg.Status, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Currency,
		&i.BillingCycle,
		&i.NextBillingDate,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.AutoRenew,
		&i.ReminderEnabled,
		&i.ReminderDaysBefore,
		&i.PaymentMethod,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
