// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_subscriptions.sql

package database

import (
	"context"
	"time"
)

const addSubscriptionToUser = `-- name: AddSubscriptionToUser :one
INSERT INTO users_subscriptions (
    user_id, subscription_id
) VALUES (
    ?, ?
)
RETURNING id, user_id, subscription_id, created_at, updated_at
`

type AddSubscriptionToUserParams struct {
	UserID         int64 `json:"user_id"`
	SubscriptionID int64 `json:"subscription_id"`
}

func (q *Queries) AddSubscriptionToUser(ctx context.Context, arg AddSubscriptionToUserParams) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, addSubscriptionToUser, arg.UserID, arg.SubscriptionID)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const calculateUserTotalMonthlyCost = `-- name: CalculateUserTotalMonthlyCost :one
SELECT SUM(
    CASE s.billing_cycle
        WHEN 'daily' THEN s.cost * 30
        WHEN 'weekly' THEN s.cost * 4.33
        WHEN 'monthly' THEN s.cost
        WHEN 'quarterly' THEN s.cost / 3
        WHEN 'yearly' THEN s.cost / 12
    END
) as total_monthly_cost
FROM subscriptions s
JOIN users_subscriptions us ON s.id = us.subscription_id
WHERE us.user_id = ? AND s.status = 'active' AND s.currency = ?
`

type CalculateUserTotalMonthlyCostParams struct {
	UserID   int64   `json:"user_id"`
	Currency *string `json:"currency"`
}

func (q *Queries) CalculateUserTotalMonthlyCost(ctx context.Context, arg CalculateUserTotalMonthlyCostParams) (*float64, error) {
	row := q.db.QueryRowContext(ctx, calculateUserTotalMonthlyCost, arg.UserID, arg.Currency)
	var total_monthly_cost *float64
	err := row.Scan(&total_monthly_cost)
	return total_monthly_cost, err
}

const calculateUserTotalYearlyCost = `-- name: CalculateUserTotalYearlyCost :one
SELECT SUM(
    CASE s.billing_cycle
        WHEN 'daily' THEN s.cost * 365
        WHEN 'weekly' THEN s.cost * 52
        WHEN 'monthly' THEN s.cost * 12
        WHEN 'quarterly' THEN s.cost * 4
        WHEN 'yearly' THEN s.cost
    END
) as total_yearly_cost
FROM subscriptions s
JOIN users_subscriptions us ON s.id = us.subscription_id
WHERE us.user_id = ? AND s.status = 'active' AND s.currency = ?
`

type CalculateUserTotalYearlyCostParams struct {
	UserID   int64   `json:"user_id"`
	Currency *string `json:"currency"`
}

func (q *Queries) CalculateUserTotalYearlyCost(ctx context.Context, arg CalculateUserTotalYearlyCostParams) (*float64, error) {
	row := q.db.QueryRowContext(ctx, calculateUserTotalYearlyCost, arg.UserID, arg.Currency)
	var total_yearly_cost *float64
	err := row.Scan(&total_yearly_cost)
	return total_yearly_cost, err
}

const countSubscriptionsByUser = `-- name: CountSubscriptionsByUser :one
SELECT COUNT(*) FROM users_subscriptions
WHERE user_id = ?
`

func (q *Queries) CountSubscriptionsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSubscriptions = `-- name: CountUserSubscriptions :one
SELECT COUNT(*) FROM users_subscriptions
`

func (q *Queries) CountUserSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersBySubscription = `-- name: CountUsersBySubscription :one
SELECT COUNT(*) FROM users_subscriptions
WHERE subscription_id = ?
`

func (q *Queries) CountUsersBySubscription(ctx context.Context, subscriptionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersBySubscription, subscriptionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserActiveSubscriptions = `-- name: GetUserActiveSubscriptions :many
SELECT s.id, s.category_id, s.name, s.description, s.cost, s.currency, s.billing_cycle, s.next_billing_date, s.start_date, s.end_date, s.status, s.auto_renew, s.reminder_enabled, s.reminder_days_before, s.payment_method, s.notes, s.created_at, s.updated_at
FROM subscriptions s
JOIN users_subscriptions us ON s.id = us.subscription_id
WHERE us.user_id = ? AND s.status = 'active'
ORDER BY s.next_billing_date ASC
`

func (q *Queries) GetUserActiveSubscriptions(ctx context.Context, userID int64) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserActiveSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT id, user_id, subscription_id, created_at, updated_at FROM users_subscriptions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserSubscription(ctx context.Context, id int64) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscription, id)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscriptionsByCategory = `-- name: GetUserSubscriptionsByCategory :many
SELECT s.id, s.category_id, s.name, s.description, s.cost, s.currency, s.billing_cycle, s.next_billing_date, s.start_date, s.end_date, s.status, s.auto_renew, s.reminder_enabled, s.reminder_days_before, s.payment_method, s.notes, s.created_at, s.updated_at
FROM subscriptions s
JOIN users_subscriptions us ON s.id = us.subscription_id
WHERE us.user_id = ? AND s.category_id = ?
ORDER BY s.next_billing_date ASC
`

type GetUserSubscriptionsByCategoryParams struct {
	UserID     int64 `json:"user_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) GetUserSubscriptionsByCategory(ctx context.Context, arg GetUserSubscriptionsByCategoryParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptionsByCategory, arg.UserID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscriptionsCreatedAfter = `-- name: GetUserSubscriptionsCreatedAfter :many
SELECT id, user_id, subscription_id, created_at, updated_at FROM users_subscriptions
WHERE created_at > ?
ORDER BY created_at DESC
`

func (q *Queries) GetUserSubscriptionsCreatedAfter(ctx context.Context, createdAt *time.Time) ([]UsersSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptionsCreatedAfter, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersSubscription{}
	for rows.Next() {
		var i UsersSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscriptionsWithDetails = `-- name: GetUserSubscriptionsWithDetails :many
SELECT
    us.id, us.user_id, us.subscription_id, us.created_at, us.updated_at,
    u.name as user_name,
    u.email as user_email,
    s.name as subscription_name,
    s.cost as subscription_cost,
    s.currency as subscription_currency,
    s.billing_cycle as billing_cycle,
    s.next_billing_date as next_billing_date,
    s.status as subscription_status
FROM users_subscriptions us
JOIN users u ON us.user_id = u.id
JOIN subscriptions s ON us.subscription_id = s.id
WHERE us.user_id = ?
ORDER BY s.next_billing_date ASC
`

type GetUserSubscriptionsWithDetailsRow struct {
	ID                   int64      `json:"id"`
	UserID               int64      `json:"user_id"`
	SubscriptionID       int64      `json:"subscription_id"`
	CreatedAt            *time.Time `json:"created_at"`
	UpdatedAt            *time.Time `json:"updated_at"`
	UserName             string     `json:"user_name"`
	UserEmail            string     `json:"user_email"`
	SubscriptionName     string     `json:"subscription_name"`
	SubscriptionCost     float64    `json:"subscription_cost"`
	SubscriptionCurrency *string    `json:"subscription_currency"`
	BillingCycle         string     `json:"billing_cycle"`
	NextBillingDate      time.Time  `json:"next_billing_date"`
	SubscriptionStatus   *string    `json:"subscription_status"`
}

func (q *Queries) GetUserSubscriptionsWithDetails(ctx context.Context, userID int64) ([]GetUserSubscriptionsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptionsWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserSubscriptionsWithDetailsRow{}
	for rows.Next() {
		var i GetUserSubscriptionsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.SubscriptionName,
			&i.SubscriptionCost,
			&i.SubscriptionCurrency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.SubscriptionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUpcomingRenewals = `-- name: GetUserUpcomingRenewals :many
SELECT s.id, s.category_id, s.name, s.description, s.cost, s.currency, s.billing_cycle, s.next_billing_date, s.start_date, s.end_date, s.status, s.auto_renew, s.reminder_enabled, s.reminder_days_before, s.payment_method, s.notes, s.created_at, s.updated_at
FROM subscriptions s
JOIN users_subscriptions us ON s.id = us.subscription_id
WHERE us.user_id = ?
  AND s.status = 'active'
  AND s.next_billing_date BETWEEN CURRENT_DATE AND DATE(CURRENT_DATE, '+' || ? || ' days')
ORDER BY s.next_billing_date ASC
`

type GetUserUpcomingRenewalsParams struct {
	UserID  int64   `json:"user_id"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) GetUserUpcomingRenewals(ctx context.Context, arg GetUserUpcomingRenewalsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserUpcomingRenewals, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many
SELECT s.id, s.category_id, s.name, s.description, s.cost, s.currency, s.billing_cycle, s.next_billing_date, s.start_date, s.end_date, s.status, s.auto_renew, s.reminder_enabled, s.reminder_days_before, s.payment_method, s.notes, s.created_at, s.updated_at
FROM subscriptions s
JOIN users_subscriptions us ON s.id = us.subscription_id
WHERE us.user_id = ?
ORDER BY s.next_billing_date ASC
`

func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID int64) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Currency,
			&i.BillingCycle,
			&i.NextBillingDate,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.AutoRenew,
			&i.ReminderEnabled,
			&i.ReminderDaysBefore,
			&i.PaymentMethod,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT id, user_id, subscription_id, created_at, updated_at FROM users_subscriptions
ORDER BY created_at DESC
`

func (q *Queries) ListUserSubscriptions(ctx context.Context) ([]UsersSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersSubscription{}
	for rows.Next() {
		var i UsersSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersBySubscription = `-- name: ListUsersBySubscription :many
SELECT u.id, u.email, u.password, u.name, u.created_at, u.updated_at
FROM users u
JOIN users_subscriptions us ON u.id = us.user_id
WHERE us.subscription_id = ?
ORDER BY u.name
`

func (q *Queries) ListUsersBySubscription(ctx context.Context, subscriptionID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllSubscriptionsFromUser = `-- name: RemoveAllSubscriptionsFromUser :exec
DELETE FROM users_subscriptions
WHERE user_id = ?
`

func (q *Queries) RemoveAllSubscriptionsFromUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllSubscriptionsFromUser, userID)
	return err
}

const removeAllUsersFromSubscription = `-- name: RemoveAllUsersFromSubscription :exec
DELETE FROM users_subscriptions
WHERE subscription_id = ?
`

func (q *Queries) RemoveAllUsersFromSubscription(ctx context.Context, subscriptionID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllUsersFromSubscription, subscriptionID)
	return err
}

const removeSubscriptionFromUser = `-- name: RemoveSubscriptionFromUser :exec
DELETE FROM users_subscriptions
WHERE user_id = ? AND subscription_id = ?
`

type RemoveSubscriptionFromUserParams struct {
	UserID         int64 `json:"user_id"`
	SubscriptionID int64 `json:"subscription_id"`
}

func (q *Queries) RemoveSubscriptionFromUser(ctx context.Context, arg RemoveSubscriptionFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeSubscriptionFromUser, arg.UserID, arg.SubscriptionID)
	return err
}

const removeUserSubscription = `-- name: RemoveUserSubscription :exec
DELETE FROM users_subscriptions
WHERE id = ?
`

func (q *Queries) RemoveUserSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeUserSubscription, id)
	return err
}

const userHasSubscription = `-- name: UserHasSubscription :one
SELECT EXISTS(
    SELECT 1 FROM users_subscriptions
    WHERE user_id = ? AND subscription_id = ?
)
`

type UserHasSubscriptionParams struct {
	UserID         int64 `json:"user_id"`
	SubscriptionID int64 `json:"subscription_id"`
}

func (q *Queries) UserHasSubscription(ctx context.Context, arg UserHasSubscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userHasSubscription, arg.UserID, arg.SubscriptionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
