// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_categories.sql

package database

import (
	"context"
	"time"
)

const addCategoryToUser = `-- name: AddCategoryToUser :one
INSERT INTO users_categories (
    user_id, category_id
) VALUES (
    ?, ?
)
RETURNING id, user_id, category_id, created_at, updated_at
`

type AddCategoryToUserParams struct {
	UserID     int64 `json:"user_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) AddCategoryToUser(ctx context.Context, arg AddCategoryToUserParams) (UsersCategory, error) {
	row := q.db.QueryRowContext(ctx, addCategoryToUser, arg.UserID, arg.CategoryID)
	var i UsersCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCategoriesByUser = `-- name: CountCategoriesByUser :one
SELECT COUNT(*) FROM users_categories
WHERE user_id = ?
`

func (q *Queries) CountCategoriesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCategories = `-- name: CountUserCategories :one
SELECT COUNT(*) FROM users_categories
`

func (q *Queries) CountUserCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByCategory = `-- name: CountUsersByCategory :one
SELECT COUNT(*) FROM users_categories
WHERE category_id = ?
`

func (q *Queries) CountUsersByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCategoriesCreatedAfter = `-- name: GetUserCategoriesCreatedAfter :many
SELECT id, user_id, category_id, created_at, updated_at FROM users_categories
WHERE created_at > ?
ORDER BY created_at DESC
`

func (q *Queries) GetUserCategoriesCreatedAfter(ctx context.Context, createdAt *time.Time) ([]UsersCategory, error) {
	rows, err := q.db.QueryContext(ctx, getUserCategoriesCreatedAfter, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersCategory{}
	for rows.Next() {
		var i UsersCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategoriesWithDetails = `-- name: GetUserCategoriesWithDetails :many
SELECT
    uc.id, uc.user_id, uc.category_id, uc.created_at, uc.updated_at,
    u.name as user_name,
    u.email as user_email,
    c.name as category_name,
    c.description as category_description
FROM users_categories uc
JOIN users u ON uc.user_id = u.id
JOIN categories c ON uc.category_id = c.id
WHERE uc.user_id = ?
ORDER BY c.name
`

type GetUserCategoriesWithDetailsRow struct {
	ID                  int64      `json:"id"`
	UserID              int64      `json:"user_id"`
	CategoryID          int64      `json:"category_id"`
	CreatedAt           *time.Time `json:"created_at"`
	UpdatedAt           *time.Time `json:"updated_at"`
	UserName            string     `json:"user_name"`
	UserEmail           string     `json:"user_email"`
	CategoryName        string     `json:"category_name"`
	CategoryDescription *string    `json:"category_description"`
}

func (q *Queries) GetUserCategoriesWithDetails(ctx context.Context, userID int64) ([]GetUserCategoriesWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCategoriesWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserCategoriesWithDetailsRow{}
	for rows.Next() {
		var i GetUserCategoriesWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.CategoryName,
			&i.CategoryDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategory = `-- name: GetUserCategory :one
SELECT id, user_id, category_id, created_at, updated_at FROM users_categories
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserCategory(ctx context.Context, id int64) (UsersCategory, error) {
	row := q.db.QueryRowContext(ctx, getUserCategory, id)
	var i UsersCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT c.id, c.name, c.description, c.created_at, c.updated_at
FROM categories c
JOIN users_categories uc ON c.id = uc.category_id
WHERE uc.user_id = ?
ORDER BY c.name
`

func (q *Queries) ListCategoriesByUser(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCategories = `-- name: ListUserCategories :many
SELECT id, user_id, category_id, created_at, updated_at FROM users_categories
ORDER BY created_at DESC
`

func (q *Queries) ListUserCategories(ctx context.Context) ([]UsersCategory, error) {
	rows, err := q.db.QueryContext(ctx, listUserCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersCategory{}
	for rows.Next() {
		var i UsersCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCategory = `-- name: ListUsersByCategory :many
SELECT u.id, u.email, u.password, u.name, u.created_at, u.updated_at
FROM users u
JOIN users_categories uc ON u.id = uc.user_id
WHERE uc.category_id = ?
ORDER BY u.name
`

func (q *Queries) ListUsersByCategory(ctx context.Context, categoryID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllCategoriesFromUser = `-- name: RemoveAllCategoriesFromUser :exec
DELETE FROM users_categories
WHERE user_id = ?
`

func (q *Queries) RemoveAllCategoriesFromUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllCategoriesFromUser, userID)
	return err
}

const removeAllUsersFromCategory = `-- name: RemoveAllUsersFromCategory :exec
DELETE FROM users_categories
WHERE category_id = ?
`

func (q *Queries) RemoveAllUsersFromCategory(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllUsersFromCategory, categoryID)
	return err
}

const removeCategoryFromUser = `-- name: RemoveCategoryFromUser :exec
DELETE FROM users_categories
WHERE user_id = ? AND category_id = ?
`

type RemoveCategoryFromUserParams struct {
	UserID     int64 `json:"user_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) RemoveCategoryFromUser(ctx context.Context, arg RemoveCategoryFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeCategoryFromUser, arg.UserID, arg.CategoryID)
	return err
}

const removeUserCategory = `-- name: RemoveUserCategory :exec
DELETE FROM users_categories
WHERE id = ?
`

func (q *Queries) RemoveUserCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeUserCategory, id)
	return err
}

const userHasCategory = `-- name: UserHasCategory :one
SELECT EXISTS(
    SELECT 1 FROM users_categories
    WHERE user_id = ? AND category_id = ?
)
`

type UserHasCategoryParams struct {
	UserID     int64 `json:"user_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) UserHasCategory(ctx context.Context, arg UserHasCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userHasCategory, arg.UserID, arg.CategoryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
